name: Terraform Deploy (Workspaces)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Terraform Workspace (Environment)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stage
          - prod

jobs:
  terraform:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
  with:
    terraform_version: 1.6.6

    - name: Check Terraform version
      run: terraform version

    - name: Terraform Init
      run: terraform init

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Init
      run: terraform init

    - name: Select Workspace
      run: |
        terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
